---
- name: install sublime 3
  mac_pkg: pkg_type=app
           url=http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203083.dmg
           archive_type=dmg archive_path='Sublime Text.app'
  become: yes
