---
- name: get oh-my-zsh script
  get_url: url=http://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh dest=/tmp/oh-my-zsh.sh

- name: change file permission to be executable
  command: chmod +x /tmp/oh-my-zsh.sh

- name: install zsh
  script: /tmp/oh-my-zsh.sh
